DROP DATABASE QLCOVUA
CREATE DATABASE QLCOVUA

USE QLCOVUA

CREATE TABLE NGUOIDUNG(
	TENND VARCHAR(20) NOT NULL,
	MATKHAU VARCHAR(20),
	EMAIL VARCHAR(30),
	DIEM BIGINT,
	CONSTRAINT PK01 PRIMARY KEY(TENND))

/*THUA -2, HÒA +1, THẮNG +5, NẾU THUA MÀ ĐIỂM <2 THÌ DIEM = 0*/

CREATE TABLE BANCHOI(
	MABC INT NOT NULL IDENTITY(1,1),
	TENND VARCHAR(20),
	KQUA INT)
/*KQUA 0:THUA, 1:HÒA, 2:THẮNG*/

ALTER TABLE BANCHOI ADD CONSTRAINT FK01 FOREIGN KEY(TENND) REFERENCES NGUOIDUNG(TENND);


INSERT INTO NGUOIDUNG VALUES ('ANDINH','1234','an.dinh201@gm',11);
INSERT INTO NGUOIDUNG VALUES ('ANDINH123','1111','an.dinh000@gm',5);
INSERT INTO NGUOIDUNG VALUES ('thanhhang','0000','hang2312@gm',1);
INSERT INTO NGUOIDUNG VALUES ('HUNGSON','AAAAA','son2345@gm',0);
 
INSERT INTO BANCHOI VALUES ('ANDINH',2);
INSERT INTO BANCHOI VALUES ('ANDINH123',0);
INSERT INTO BANCHOI VALUES ('ANDINH',1);
INSERT INTO BANCHOI VALUES ('thanhhang',1);
INSERT INTO BANCHOI VALUES ('ANDINH123',2);
INSERT INTO BANCHOI VALUES ('THANHHANG',0);
INSERT INTO BANCHOI VALUES ('THANHHANG',1);
INSERT INTO BANCHOI VALUES ('HUNGSON',1);
INSERT INTO BANCHOI VALUES ('ANDINH',2);
INSERT INTO BANCHOI VALUES ('HUNGSON',0);





select * from nguoidung
SELECT * FROM BANCHOI

/*delete from nguoidung where tennd='hungson'

select top 3 diem, tennd from nguoidung order by diem desc
update nguoidung set DIEM = 0 where mand=2
DROP TABLE NGUOIDUNG
DROP TABLE BANCHOI*/


